name: hexlet-tests

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
      - run: make install
      - run: make lint
      - run: make test